### ISSUE TITLE
Segmentation fault when attempting to open duplicate camservers

### ISSUE THREAD

**Issue by electron-wranglers** [dhm-org/dhm_suite#6]
When running camserver using a single camera, running another instance of camserver causes a segmentation fault.

Using:
Allied 2450 via GigE-USB-C converter
Vimba 2.1 drivers
Ubuntu 18.04 LTS

Steps to reproduce
- run camserver with './camserver' using no options
- in another terminal type './camserver'

Error message:

Start Camera Server...
Access camera 0, width_in=2048, height_in=2048, rate_in=15.000000
Error.  Unable to open CAMERA 0
Start Camera Server
Segmentation fault (core dumped)

**Comment by sfregoso** [comment]
The segmentation fault occurs when the camserver attempts to open a camera that is already being used either by another instance of the camserver or by the VimbaViewer.  The proper solution is to not segfault.  Will work on this.

**Comment by electron-wranglers** [comment]
I should add that the branch where I observed this error was in the master branch. I have been unable to reproduce this bug in the development branch.
