### ISSUE TITLE
Reconstruction dies when opening reconstruction settings window

### ISSUE THREAD

**Issue by electron-wranglers** [dhm-org/dhm_suite#7]
Steps to reproduce: 

- open dhmsw 
- set any of the reconstruction modes
- open Amplitude, intensity, or phase reconstruction
- open reconstruction settings window

The result is the reconstruction displays either no content or all zero intensity pixels(depending on the reconstruction window was opened WRT the settings). Afterwards, reconstruction cannot be used until the software is restarted.

**Comment by MrWizard2000** [comment]
Is this issue happening when you use the DHMx GUI? (the dhm-gui)?  And the displays are receiving empty data? (All 0 / blue display?)

**Comment by electron-wranglers** [comment]
Yes, if I have a reconstruction window running when I open the settings, it displays all 0 pixels (blue). If I leave a reconstruction window closed until after opening the settings window, then the window has no display at all (background color of the frame the reconstruction is displayed in.

**Comment by MrWizard2000** [comment]
Tested and confirmed the issue.  It looks like both amplitude and/or intensity stop functioning, however fourier continues to work.  I will assign this to Felipe and I will look into this further.

**Comment by MrWizard2000** [comment]
Issue found.  Reconstruction window is setting propagation distance to 0 and reconstructor does not like that value:
ACK: reconst propagation_distance=[0]
Setting it to any other value other than 0 (e.g 0.01) will show the reconstruction again.

confirmed that default value of propagation distance on startup from dhmsw (using reconst command) is:
[0.009999999776482582, 0.0, 0.0]

**Comment by electron-wranglers** [comment]
Nice work! I have additional questions regarding the propagation distance (as well as the x and y dimension pitch values in the workspace settings. What are / should these values be used for?
It seems that changing either x or y pitch values from the default of 3.450 causes erratic behavior in the appearance of the reconstructed image (like crazy distortion), or no image at all. Curious for more info!

**Comment by MrWizard2000** [comment]
> Nice work! I have additional questions regarding the propagation distance (as well as the x and y dimension pitch values in the workspace settings. What are / should these values be used for?
> It seems that changing either x or y pitch values from the default of 3.450 causes erratic behavior in the appearance of the reconstructed image (like crazy distortion), or no image at all.
> 
> If these values are produced from distances or parameters of my recording setup that I could measure empirically that would be best. Curious for more info!

This would be a question more for @sfregoso 
I will look into it though and see if I can provide any helpful info!

**Comment by electron-wranglers** [comment]
Closing issue - problem solved.
